name: flutter_jimtl
description: Intl utility to use ARB files without code generation, deal with ARB flavors and have ARB OTA updates in your app
version: 0.0.1
homepage: https://github.com/jaumard/jimtl

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <1.0.0"
  jimtl: ">=0.0.1 <1.0.0"
  #path: '../jimtl'

dev_dependencies:
  test:
