name: jimtl
description: Intl utility to use ARB files without code generation, deal with ARB flavors and have ARB OTA updates in your app
version: 0.0.7
homepage: https://github.com/jaumard/jimtl

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ">=0.17.0 <1.0.0"
  intl_generator: ">=0.4.1 <1.0.0"

dev_dependencies:
  test:
